name: CI

on:
    - push
    - pull_request

jobs:
    ci:
        # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners
        runs-on: ubuntu-latest
        steps:
            # https://github.com/marketplace/actions/checkout
            - uses: actions/checkout@v4.2.2
            # https://github.com/marketplace/actions/setup-node-js-environment
            - uses: actions/setup-node@v4.4.0
              with:
                  node-version: "22.x"
            # https://github.com/marketplace/actions/cache
            - uses: actions/cache@v4.2.3
              with:
                  path: ~/.local/share/pnpm/store
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: ${{ runner.os }}-pnpm-
            - run: |
                  corepack enable
                  # https://www.npmjs.com/package/pnpm
                  corepack prepare pnpm@10.9.0 --activate
                  pnpm config set store-dir ~/.local/share/pnpm/store
                  pnpm install
              env:
                  PNPM_HOME: /home/runner/.local/bin
            - run: make -j build lint test
