name: release

on:
    workflow_dispatch:
        inputs:
            version:
                description: "version"
                type: "choice"
                required: true
                default: "minor"
                options:
                    - "major"
                    - "minor"
                    - "patch"
                    - "premajor"
                    - "preminor"
                    - "prepatch"
                    - "prerelease"

jobs:
    release:
        # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners
        runs-on: ubuntu-latest
        permissions:
            contents: write
            id-token: write
        steps:
            # https://github.com/marketplace/actions/checkout
            - uses: actions/checkout@v4.2.2
            # https://github.com/marketplace/actions/setup-node-js-environment
            - uses: actions/setup-node@v4.4.0
              with:
                  node-version: "22.x"
                  registry-url: "https://registry.npmjs.org"
            # https://github.com/marketplace/actions/cache
            - uses: actions/cache@v4.2.3
              with:
                  path: ~/.local/share/pnpm/store
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: ${{ runner.os }}-pnpm-
            - run: |
                  # https://www.npmjs.com/package/pnpm
                  npm install -g pnpm@10.9.0
                  pnpm config set store-dir ~/.local/share/pnpm/store
                  pnpm install
              env:
                  PNPM_HOME: /home/runner/.local/bin
            - run: make -j build lint test
            - run: |
                  git config --global user.name "GitHub Actions (${GITHUB_ACTOR})"
                  git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
            - run: |
                  make doc
                  git add .
                  git commit -m "[skip ci] doc"
            - run: npm version ${VERSION}
              env:
                  VERSION: ${{ inputs.version }}
            - run: npm publish --provenance --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
            - run: |
                  git push
                  git push --tags
